name: 'Version Checker'
description: 'Check if package version in package.json is higher than the current package version on npm'
inputs:
  localFilePath:
    description: 'file path to your package.json'
    required: true
  publicPackageName:
    description: 'name of your package as listed on npm'
    required: true
outputs:
  localVersion:
    description: 'version number of local package'
  publicVersion:
    description: 'version number of package on npm'
  updated:
    description: 'wether the local version num has been updated compared to public version num'
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'