name: versionCheckerTest

on: [push]

jobs:

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - run: npm install
      - uses: CharlieHodgkinson/VersionChecker@master
        with:
          localFilePath: '/home/runner/work/VersionChecker/VersionChecker/package.json'
          publicPackageName: 'charlie-citest'
      - continue-on-error: true
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success"